### ISSUE TITLE
will you open source the training code?

### ISSUE THREAD

**Issue by gaopeng-eugene** [ZheC/Realtime_Multi-Person_Pose_Estimation#1]

**Comment by ZheC** [comment]
Yes, we will release the training code in this repository soon (about two weeks later).

**Comment by sndler** [comment]
pretty cool

**Comment by sndler** [comment]
I am very interested in your methods, and how long will you open sources the training code? Thanks

**Comment by ShangxuanWu** [comment]
Is there any special layers in your training network? If not, I could rewrite it in tensorflow.

**Comment by power0341** [comment]
Awesome demo! and can't wait to try the training code. thanks

**Comment by sndler** [comment]
Thanks for your reply! there is no special layer. I have read your paper, but have some questions ,something not understand, so I want to understand your work better using your training code. My email address is sndlytp@sjtu.edu.cn    Sincerely thanks!

**Comment by KeyKy** [comment]
I also try the test code and can't wait to read your training code!

**Comment by ZheC** [comment]
Thank you all for the interest. We are trying our best to make training easy for you guys to use or modify. It seems that we need a little more time to do this because we have tested hundreds of experiments, making our performance better but the code messier. 

For those who cannot wait longer to try the training code, here is a temporary repo for our modified caffe: https://github.com/CMU-Perceptual-Computing-Lab/caffe_train

We will soon merge it with our testing caffe soon (https://github.com/CMU-Perceptual-Computing-Lab/caffe_rtpose). We will focus on making a clean training version for easier usage rather than maintaining the temporary repo (it will be replaced in the end). Thanks for understanding!

**Comment by sndler** [comment]
Much Thanks!

**Comment by sndler** [comment]
when python SetLayers.py, there is an error as following:
ERROR :AttributeError: 'LayerParameter' object has no attribute 'cpm_transform_param'   
How to solve this error ,Thanks!

**Comment by ZheC** [comment]
In line 12 of setLayers.py, you need to specify the directory to caffe_train, instead of your own caffe. The attribute 'cpm_transform_param' is in our version of caffe.

**Comment by raymon-tian** [comment]
A new hand, can't wait to read the training code!

**Comment by sndler** [comment]
why the joints location is larger than the image's size ?  
eg:
joint : #
![image](https://cloud.githubusercontent.com/assets/13741504/22053577/8905bb9a-dd8c-11e6-9141-6ecf230bf894.png)

but the frame's size is 
![image](https://cloud.githubusercontent.com/assets/13741504/22053594/a8b78090-dd8c-11e6-990b-bc7ffc17ab04.png)

Is the scale? 


Thanks.

**Comment by gineshidalgo99** [comment]
The joints are scaled to the final frame resolution (by default 1280 x 720). You can modify the final resolution with the `--resolution` flag.

**Comment by ResByte** [comment]
Hi ZheC, 
I am trying to train from scratch using your repo and caffe_rtpose on mscoco. I have been referencing your recent paper also. Can you share training details, as how long does it take to train(on what gpu)? what are the specific parameters(like input image size ) for training?

Thanks.

**Comment by ZheC** [comment]
Hi,

We have released the training parameters in https://github.com/ZheC/Realtime_Multi-Person_Pose_Estimation/tree/master/training

Specifically, you can set the parameters in https://github.com/ZheC/Realtime_Multi-Person_Pose_Estimation/blob/master/training/setLayers.py

pose_train_test.prototxt and pose_solver.prototx are example training files.

**Comment by shoCaffeTeria** [comment]
Great Work! 
But I can't wait for your code to generate LMDB!!
Thanks

**Comment by ZheC** [comment]
@shoCaffeTeria I have added the code for generating LMDB in 'training' folder and the process in READEME file. I have tested them on my computer. Let me know if you meet any problem.

**Comment by shoCaffeTeria** [comment]
Thank u very much!
I want to try it soon, but my PC is in repairing now :-(

**Comment by ZheC** [comment]
@sndler I have fixed the issue of  "AttributeError: 'LayerParameter' object has no attribute 'cpm_transform_param'" with an updated caffe_train(https://github.com/CMU-Perceptual-Computing-Lab/caffe_train). Also, it uses a newer version of caffe so that it is compatible with CUDA 7.5/ 8.0 and cudnn v5. Let me know if you meet other issues. Thanks!

**Comment by shoCaffeTeria** [comment]
Hi , ZheC
Your genLMBD code works well. 
Thanks
