### ISSUE TITLE
Zero Division in Python example

### ISSUE THREAD

**Issue by ggalan87** [ZheC/Realtime_Multi-Person_Pose_Estimation#54]
Hello. In some cases the python demo results to ZeroDivisionError which is produced by the code: `vec = np.divide(vec, norm) (demo.ipynb, In [72])`. 

The  relevant C++ code (rtpose.cpp, line 620) handles this case as follows `if (norm_vec<1e-6) { continue; }`. So I think a similar fix should be applied.

**Comment by iqbalu** [comment]
Hello,

The error occurs when peaks for two different parts are detected at the same locations. In that case the norm becomes zeros. This is a typical numerical issue. I think in the simplest case one can fix it by adding a small number to the norm. e.g., 

norm = norm + 1e-5

Hope that helps.

**Comment by liviust** [comment]
Hi @iqbalu  @ZheC  @ggalan87 

I've noticed that the python code doesn't reproduce exactly the matlab version. Also, the fast fix posted by @iqbalu leads to this: 
<img width="221" alt="capture" src="https://cloud.githubusercontent.com/assets/25505723/26113262/5f665436-3a5a-11e7-97fa-8d7d15fa45b0.PNG">

**Comment by ggalan87** [comment]
I haven't run either C++ or Matlab versions but I have some images that python code leads to more or less what @liviust posted as example output and also some other cases. I can collect them and post them, but I think that they are just an acceptable portion of algorithm failures.

**Comment by iqbalu** [comment]
Do you get similar results for all images, or just a few?
![figure_1](https://cloud.githubusercontent.com/assets/5772474/26115191/95032772-3a5f-11e7-9b5f-cb531ef20cf7.png)

This is what I get with the python code.

**Comment by liviust** [comment]
Hi @iqbalu , @ggalan87 

The problem is not always visible. Let's take the image from the sample_image folder [ski.jpg], and run the code. Visually everything looks ok, but if we analyse it in depth, we will see the effect of the bug.

Let's run this code on the ski.jpg image:

It should print the coordinates of the joints per subject.
```
for i in range(len(subset)-1):
    subtJoints = pd.DataFrame([d[i] for d in all_peaks])
    print('Subject %d') %i
    print(subtJoints[0], subtJoints[1])
```

and it showed:
Subject 0
(0 615
1 616
2 580
3 545
4 283
5 648
6 654
7 657
8 610
9 620
10 619
11 651
12 340
13 294
14 606
15 621
16 593
17 626
Name: 0, dtype: int64, 0 33
1 75
2 87
3 123
4 167
5 72
6 120
7 159
8 197
9 280
10 363
11 193
12 277
13 344
14 30
15 30
16 34
17 31
Name: 1, dtype: int64)
Subject 1
(0 296
1 298
2 267
3 340
4 565
5 331
6 349
7 563
8 294
9 305
10 313
11 335
12 650
13 636
14 294
15 299
16 280
17 312
Name: 0, dtype: int64, 0 73
1 106
2 116
3 135
4 171
5 105
6 149
7 185
8 212
9 282
10 365
11 210
12 278
13 358
14 62
15 62
16 72
17 65
Name: 1, dtype: int64)
Subject 2
(0 475
1 457
2 414
3 253
4 74
5 502
6 535
7 93
8 438
9 74
10 117
11 457
12 104
13 161
14 462
15 486
16 434
17 75
Name: 0, dtype: int64, 0 91
1 136
2 136
3 162
4 343
5 135
6 182
7 354
8 322
9 347
10 404
11 314
12 341
13 407
14 78
15 76
16 88
17 269
Name: 1, dtype: int64)
Subject 3
(0 60
1 59
2 30
3 59
4 162
5 89
6 117
7 189
8 147
9 504
10 532
11 181
12 236
13 403
14 57
15 63
16 43
17 180
Name: 0, dtype: int64, 0 269
1 301
2 301
3 343
4 376
5 301
6 331
7 375
8 375
9 434
10 571
11 373
12 366
13 574
14 258
15 259
16 269
17 274
Name: 1, dtype: int64)

 Let's take subject 0. and look at the coordinates by opening the image in matlab for example:

Subject 0
(0 615
1 616
2 580
3 545
4 283
5 648
6 654
7 657
8 610
9 620
10 619
11 651
12 340
13 294
14 606
15 621
16 593
17 626
Name: 0, dtype: int64, 0 33
1 75
2 87
3 123
4 167
5 72
6 120
7 159
8 197
9 280
10 363
11 193
12 277
13 344
14 30
15 30
16 34
17 31
Name: 1, dtype: int64)

Check the coordinates from the index 12 (340,277) we see that the joint belongs to another subject, not to subject 0. The same happens with the coordinates from the indexes 4 and 13. In the matlab version this doesn't happen, so it's a small bug somewhere.

Thank you!

**Comment by ggalan87** [comment]
Most of the wrong results (including one similar to @liviust picture) that I mentioned above where due to the fact that I accidentally deleted the normalization when I fixed the ZeroDivisionError. I'm closing the issue and I will open another one regarding the rest cases.

@liviust I replied to issue #57 that you opened regarding the mixed joints indices.

**Comment by legan78** [comment]
@liviust @iqbalu have you tested the python code to generate the json for coco evaluation? If so, what is the average precision you obtained?
